version: ¨3.8¨
services:
 db:
    image: postgres
    container_name: camagru42_db
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        - ./db:/var/lib/postgresql/data

 backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
        - ./backend/src:/var/www/html
    ports:
        - "80:80"
    networks:
        - camagru42
    depends_on:
        - db


networks:
    camagru42:
        driver: bridge
